In [19]:
# pip install numpy 
# pip install pandas

In [20]:
import numpy as np

In [21]:
arr_1n = np.array([2,6,8,1,9,4,3])
arr_1n.ndim

1

In [22]:
arr_2n = np.array([[4,2,6,1,7],[6,2,7,8,1], [9,22,6,0,7] ])
arr_2n.ndim

2

In [23]:
arr = np.array([[[4,2,6,1,7],[6,2,7,8,1], [9,22,6,0,7] ],
[[4,2,6,1,7],[6,2,7,8,1], [9,22,6,0,7] ],
[[4,2,6,1,7],[6,2,7,8,1], [9,22,6,0,7] ]])
arr.ndim

3

In [24]:
arr = np.array([2,6,8,1,9,4,3], dtype="float32")
arr.dtype
arr

array([2., 6., 8., 1., 9., 4., 3.], dtype=float32)

In [25]:
arr = np.array([[4,2,6,1,7],[6,2,7,8,1], [9,22,6,0,7] ])
arr

array([[ 4,  2,  6,  1,  7],
       [ 6,  2,  7,  8,  1],
       [ 9, 22,  6,  0,  7]])

In [26]:
arr.reshape(5,3)

array([[ 4,  2,  6],
       [ 1,  7,  6],
       [ 2,  7,  8],
       [ 1,  9, 22],
       [ 6,  0,  7]])

In [27]:
arr_1n

array([2, 6, 8, 1, 9, 4, 3])

In [30]:
arr_1n[1:4]

array([6, 8, 1])

In [31]:
arr_2n

array([[ 4,  2,  6,  1,  7],
       [ 6,  2,  7,  8,  1],
       [ 9, 22,  6,  0,  7]])

In [41]:
# arr_2n[:3][:2]
arr_2n[:2,:2]

array([[4, 2],
       [6, 2]])

In [44]:
arr = np.zeros([3,5], dtype="int32")
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [46]:
arr = np.ones([4,8], dtype="int32")
arr

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [51]:
arr = np.arange(0,10).reshape(5,2)
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [54]:
arr = np.full([3,5], 1000, dtype="float64")
arr

array([[1000., 1000., 1000., 1000., 1000.],
       [1000., 1000., 1000., 1000., 1000.],
       [1000., 1000., 1000., 1000., 1000.]])

In [56]:
arr = np.linspace(0,10, 10)
arr

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [89]:
# random
arr = np.random.seed(1)
arr = np.random.random([3,5])
arr.reshape(5,3)

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04],
       [3.02332573e-01, 1.46755891e-01, 9.23385948e-02],
       [1.86260211e-01, 3.45560727e-01, 3.96767474e-01],
       [5.38816734e-01, 4.19194514e-01, 6.85219500e-01],
       [2.04452250e-01, 8.78117436e-01, 2.73875932e-02]])

In [114]:
arr = np.random.randint(0,10, [3,5])
arr

array([[5, 5, 4, 5, 8],
       [5, 8, 1, 1, 8],
       [7, 0, 3, 4, 2]])

In [121]:
arr = np.random.rand(3,5)
arr

array([[0.02410163, 0.45200161, 0.80833875, 0.36837685, 0.60920699],
       [0.03484772, 0.35457723, 0.07851996, 0.6931852 , 0.01271267],
       [0.45954528, 0.96131726, 0.33418522, 0.47208342, 0.10539125]])

In [124]:
arr_1n = np.array([2,6,8,1,9,4,3])
arr_2n = np.array([4,6,2,8,9,5,3])
arr = arr_1n ** arr_2n
arr

array([       16,     46656,        64,         1, 387420489,      1024,
              27])

In [134]:
# massive array
arr = np.random.random(100000000)
arr
sum(arr)

49995451.947827876

In [138]:
arr = np.random.randint(10, 1000, [3,5])
x = arr.var()
x

114335.84888888891