# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [2]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
np.version.version

'1.24.2'

#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
vector = np.zeros(10)
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [6]:
Z = np.zeros((10,10))
memory = Z.size * Z.itemsize
memory

800

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
np.info(np.info)

 info(object=None, maxwidth=76, output=None, toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``None``, in which case ``sys.stdout`` will be used.
    The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +SKIP
   polyval(p, x)
 

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
arr = np.zeros(10, dtype='int')
arr[4] = 1
arr

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
arr = np.arange(10,50,1)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [10]:
arr[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [11]:
arr = np.arange(0,9,1).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [12]:
arr = np.array([-1,2,0,0,4,0])
ar1 = np.nonzero(arr)
print(ar1)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [13]:
np.eye(3, M=4, k=1 ,dtype=int)

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [14]:
np.random.random([3,3,3])

array([[[0.01784768, 0.96030747, 0.72877657],
        [0.02776109, 0.36871656, 0.85885655],
        [0.065711  , 0.48887473, 0.79785975]],

       [[0.01499641, 0.5370211 , 0.23895613],
        [0.37687122, 0.02686976, 0.22684818],
        [0.90800648, 0.0917929 , 0.74185548]],

       [[0.09416259, 0.44496909, 0.05684629],
        [0.46388777, 0.26914872, 0.39471865],
        [0.54724764, 0.31555219, 0.34581235]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [15]:
np.random.seed(97)
arr = np.random.randint(0,100,(10,10))
min = np.ndarray.min(arr)
max = np.ndarray.max(arr)
print(f"min: {min}. max: {max}")

min: 3. max: 97


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [16]:
arr = np.random.randint(0,100,30)
arr.mean()
# np.mean(arr)

47.03333333333333

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [17]:
arr = np.ones([6,6], dtype=int)

# for indexRow, row in enumerate(arr[1:-1,1:-1]):
#     for indexCol,col in enumerate(row):
#         arr[indexRow+1,indexCol+1] =0
arr[1:-1,1:-1] = 0
arr

        

array([[1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [18]:
arr = np.ones([6,6],dtype=int)
# arr[:1] =0
# arr[-1:] =0
# arr[:,:1] =0
# arr[:,-1:] =0
np.pad(arr,(1,1), mode='constant',constant_values=(0,0))


array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [19]:
# 0*np.nan -> NaN
# np.nan == np.nan -> False
# np.inf > np.nan -> False
# np.nan - np.nan -> NaN
# np.nan in set([np.nan]) -> True
# 0.3 == 3 * 0.1 -> False nhị phân chuyển sang thập phân, 10 = 2x5, 2^n*5^m

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [20]:
arr = np.arange(1,5)
np.diag(arr,k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [21]:
arr =np.ones([8,8],dtype=int)
arr[::2,::2] = 0
arr[1::2,1::2] = 0
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [22]:
arr = np.random.randint(0,100,[6,7,8])
print(arr)
arr[np.unravel_index(0,[6,7,8])]

[[[66  7 26 94 82 10 59 50]
  [41 72 88 80 61 36 69 98]
  [17  3 68 19 43 31 99 23]
  [59 88  7 44 96 88 68 72]
  [ 3 34 27 89 99 24 21 41]
  [10 70 41 25  0 49 17  4]
  [68 63 13 76 46 90 45 46]]

 [[50 92 98 88 63 26 48 46]
  [97 31 96 62 70 15 43 68]
  [50 30 57 28 27 61 23 56]
  [72 39  7 46 43 10 61 45]
  [54 66 36  6 77 16 20 11]
  [28  0 85 59 56 46 49 33]
  [28 71 87 80  3 40 52 74]]

 [[63 15 30 45 91 47 97 50]
  [84 58 75 12 95 81 10 78]
  [27 12 71 18 73 55 87 62]
  [78  8 14 36 81 33 19 16]
  [23  4  2 41  5 73 27 87]
  [73 16 17 82 44 95 33  8]
  [27 56 11 25  0 73 22 38]]

 [[ 1 66 39 11 76  7  5 86]
  [86 51 10  6 67  7 79 84]
  [52 39 78 49 57 71 23  9]
  [69 96 31 86  0 53 58 76]
  [75 96 93 80 35 95 93 30]
  [43 69 21 92 17 53 77 59]
  [99 86 42 77 24  5 33 36]]

 [[93 49  9 56 28 63 76 19]
  [52 23 86 95 64 27 46 88]
  [66 77 85 11 95 60 59 49]
  [45 90 81 50 53 63 22 79]
  [ 8 13 54 66 45 61  7 22]
  [93 40  3 42 37 38 64  0]
  [99 76 94 83 64 52 87 92]]

 [[46 49 2

66

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [23]:
a = np.array([[0,1],[1,0]])
# a.ndim
np.tile(a,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [24]:
np.random.seed(0)
Z = np.random.random((5,5))
print(Z)
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
 [0.64589411 0.43758721 0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918 0.11827443]]
[[-0.14854421  0.44055117  0.04247881 -0.1624605  -0.59169993]
 [ 0.19519398 -0.54236874  1.06578972  1.32033341 -0.73408512]
 [ 0.71154487 -0.21907095 -0.08045184  1.18555078 -1.84023484]
 [-1.78325269 -2.02016749  0.85634317  0.66350295  0.98873998]
 [ 1.37328739  0.73786513 -0.4577726   0.67190312 -1.67297558]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [25]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [26]:
arr1 = np.random.randint(1,5,[5,3])
print(arr1)
arr2 = np.random.randint(1,5, [3,2])
print(arr2)
arr1.dot(arr2)

[[1 2 2]
 [2 4 1]
 [4 3 1]
 [4 4 3]
 [4 3 4]]
[[1 3]
 [1 1]
 [1 2]]


array([[ 5,  9],
       [ 7, 12],
       [ 8, 17],
       [11, 22],
       [11, 23]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [27]:
np.random.seed(0)
arr = np.arange(12)
arr[np.nonzero((arr >3)&(arr<8) )] *=-1
print(arr)
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [28]:
print(sum(range(5),-1))
from numpy import *
print(np.sum(range(5),-1))
print(np.sum([[1, 1], [2, 5]], axis=-1))

9
10
[2 7]


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [29]:
np.random.seed(0)
Z = np.array([[2,3,4],
             [1,2,3],
             [1,2,3]])
Y = np.array([[1,2,3],
             [3,4,5]])
# arr = np.array([2,5])
# print(np.binary_repr(arr[0]))
# print(arr)

# # arr1 = np.left_shift(arr,2)
# arr1 = 2 << arr
# print(np.binary_repr(20), np.binary_repr(np.left_shift(2,5)))
# print(np.binary_repr(arr1[0]),np.binary_repr(arr1[1]))
# print(arr1)

# # arr2 = np.right_shift(arr1,2)
# arr2 = arr >> 2
# print(np.binary_repr(arr2[0]))
# print(arr2)

# Z<Z>Z


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

In [30]:
np.random.seed(0)
Z = np.random.uniform(1,10,[4,5])
print(Z)
print(np.abs(Z))
print(np.ceil(np.abs(Z)))
print(np.copysign(np.ceil(np.abs(Z)), Z))

[[5.93932154 7.4367043  6.42487038 5.90394865 4.81289319]
 [6.81304702 4.9382849  9.02595701 9.67296484 4.45097367]
 [8.12552534 5.76005428 6.11240105 9.33036974 1.63932452]
 [1.7841637  1.18196558 8.49357861 8.00341076 8.83010933]]
[[5.93932154 7.4367043  6.42487038 5.90394865 4.81289319]
 [6.81304702 4.9382849  9.02595701 9.67296484 4.45097367]
 [8.12552534 5.76005428 6.11240105 9.33036974 1.63932452]
 [1.7841637  1.18196558 8.49357861 8.00341076 8.83010933]]
[[ 6.  8.  7.  6.  5.]
 [ 7.  5. 10. 10.  5.]
 [ 9.  6.  7. 10.  2.]
 [ 2.  2.  9.  9.  9.]]
[[ 6.  8.  7.  6.  5.]
 [ 7.  5. 10. 10.  5.]
 [ 9.  6.  7. 10.  2.]
 [ 2.  2.  9.  9.  9.]]


#### 30. How to find common values between two arrays? (★☆☆)

In [31]:
np.random.seed(1)
arr1 = np.random.randint(1,10,10)
print(arr1)
arr2 = np.random.randint(5,15,10)
print(arr2)
print(np.intersect1d(arr1,arr2,return_indices=True))

[6 9 6 1 1 2 8 7 3 5]
[10  7  9  7  9 12 12 14  6 12]
(array([6, 7, 9]), array([0, 7, 1]), array([8, 1, 2]))


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [32]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0
hint(31)

hint: np.seterr, np.errstate


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```


In [33]:
# np.emath.sqrt(-1)
# np.sqrt(-1) == np.emath.sqrt(-1) -> False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [34]:
today = np.datetime64('today')
yesterday = today - np.timedelta64(1,'D')
tomorrow = today + np.timedelta64(1,'D')
tomorrow

numpy.datetime64('2023-03-09')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [35]:
print("March, 2017")
# np.arange('2017-03', '2017-04', dtype='datetime64[D]')
np.arange('2016-07','2016-08',dtype='datetime64[D]')
answer(34)

March, 2017
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [36]:
A = np.ones(3)*1
B = np.ones(3)*2
print(B)
np.add(A,B,out=B)
print(B)
np.divide(A,2,out=A)
print(A)
np.negative(A,out=A)
print(A)
np.multiply(A,B,out=B)

[2. 2. 2.]
[3. 3. 3.]
[0.5 0.5 0.5]
[-0.5 -0.5 -0.5]


array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [37]:
np.random.seed(0)
arr = np.random.uniform(-10,10,[2,6])
print(arr)
print(np.floor(arr))
print(arr-arr%1)
print(arr.astype('int32'))
print(np.trunc(arr))
print(arr // 1)
answer(36)


[[ 0.97627008  4.30378733  2.05526752  0.89766366 -1.52690401  2.91788226]
 [-1.24825577  7.83546002  9.27325521 -2.33116962  5.83450076  0.5778984 ]]
[[ 0.  4.  2.  0. -2.  2.]
 [-2.  7.  9. -3.  5.  0.]]
[[ 0.  4.  2.  0. -2.  2.]
 [-2.  7.  9. -3.  5.  0.]]
[[ 0  4  2  0 -1  2]
 [-1  7  9 -2  5  0]]
[[ 0.  4.  2.  0. -1.  2.]
 [-1.  7.  9. -2.  5.  0.]]
[[ 0.  4.  2.  0. -2.  2.]
 [-2.  7.  9. -3.  5.  0.]]
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [46]:
np.tile(np.arange(5),(5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [69]:
def generate():
    for x in range(10):
        yield x
print(list(generate()))
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)